### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [BenjaminGuzman/bureau-custom#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by BenjaminGuzman** [comment]
@unixorn I added a screenshot in the README.md. Sorry for the very delayed response, I didn't notice this issue was open until now.
